// <auto-generated>
// Auto-generated by BabelAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Sharing
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Babel;

    /// <summary>
    /// <para>The member and type of access the member should have when added to a shared
    /// folder.</para>
    /// </summary>
    public class AddMember
    {
        #pragma warning disable 108

        /// <summary>
        /// <para>The encoder instance.</para>
        /// </summary>
        internal static enc.StructEncoder<AddMember> Encoder = new AddMemberEncoder();

        /// <summary>
        /// <para>The decoder instance.</para>
        /// </summary>
        internal static enc.StructDecoder<AddMember> Decoder = new AddMemberDecoder();

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="AddMember" /> class.</para>
        /// </summary>
        /// <param name="member">The member to add to the shared folder.</param>
        /// <param name="accessLevel">The access level to grant <paramref name="member" /> to
        /// the shared folder.  <see cref="AccessLevel.Owner" /> is disallowed.</param>
        public AddMember(MemberSelector member,
                         AccessLevel accessLevel = null)
        {
            if (member == null)
            {
                throw new sys.ArgumentNullException("member");
            }

            if (accessLevel == null)
            {
                accessLevel = AccessLevel.Viewer.Instance;
            }

            this.Member = member;
            this.AccessLevel = accessLevel;
        }

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="AddMember" /> class.</para>
        /// </summary>
        /// <remarks>This is to construct an instance of the object when
        /// deserializing.</remarks>
        public AddMember()
        {
            this.AccessLevel = AccessLevel.Viewer.Instance;
        }

        /// <summary>
        /// <para>The member to add to the shared folder.</para>
        /// </summary>
        public MemberSelector Member { get; protected set; }

        /// <summary>
        /// <para>The access level to grant <see cref="Member" /> to the shared folder.  <see
        /// cref="AccessLevel.Owner" /> is disallowed.</para>
        /// </summary>
        public AccessLevel AccessLevel { get; protected set; }

        #region Encoder class

        /// <summary>
        /// <para>Encoder for  <see cref="AddMember" />.</para>
        /// </summary>
        private class AddMemberEncoder : enc.StructEncoder<AddMember>
        {
            /// <summary>
            /// <para>Encode fields of given value.</para>
            /// </summary>
            /// <param name="value">The value.</param>
            /// <param name="writer">The writer.</param>
            public override void EncodeFields(AddMember value, enc.IJsonWriter writer)
            {
                WriteProperty("member", value.Member, writer, MemberSelector.Encoder);
                WriteProperty("access_level", value.AccessLevel, writer, AccessLevel.Encoder);
            }
        }

        #endregion


        #region Decoder class

        /// <summary>
        /// <para>Decoder for  <see cref="AddMember" />.</para>
        /// </summary>
        private class AddMemberDecoder : enc.StructDecoder<AddMember>
        {
            /// <summary>
            /// <para>Create a new instance of type <see cref="AddMember" />.</para>
            /// </summary>
            /// <returns>The struct instance.</returns>
            protected override AddMember Create()
            {
                return new AddMember();
            }

            /// <summary>
            /// <para>Set given field.</para>
            /// </summary>
            /// <param name="value">The field value.</param>
            /// <param name="fieldName">The field name.</param>
            /// <param name="reader">The json reader.</param>
            protected override void SetField(AddMember value, string fieldName, enc.IJsonReader reader)
            {
                switch (fieldName)
                {
                    case "member":
                        value.Member = MemberSelector.Decoder.Decode(reader);
                        break;
                    case "access_level":
                        value.AccessLevel = AccessLevel.Decoder.Decode(reader);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }
        }

        #endregion
    }
}
