// <auto-generated>
// Auto-generated by StoneAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.TeamCommon
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Stone;

    /// <summary>
    /// <para>The group type determines how a group is managed.</para>
    /// </summary>
    public class GroupManagementType
    {
        #pragma warning disable 108

        /// <summary>
        /// <para>The encoder instance.</para>
        /// </summary>
        internal static enc.StructEncoder<GroupManagementType> Encoder = new GroupManagementTypeEncoder();

        /// <summary>
        /// <para>The decoder instance.</para>
        /// </summary>
        internal static enc.StructDecoder<GroupManagementType> Decoder = new GroupManagementTypeDecoder();

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="GroupManagementType" />
        /// class.</para>
        /// </summary>
        public GroupManagementType()
        {
        }

        /// <summary>
        /// <para>Gets a value indicating whether this instance is CompanyManaged</para>
        /// </summary>
        public bool IsCompanyManaged
        {
            get
            {
                return this is CompanyManaged;
            }
        }

        /// <summary>
        /// <para>Gets this instance as a CompanyManaged, or <c>null</c>.</para>
        /// </summary>
        public CompanyManaged AsCompanyManaged
        {
            get
            {
                return this as CompanyManaged;
            }
        }

        /// <summary>
        /// <para>Gets a value indicating whether this instance is UserManaged</para>
        /// </summary>
        public bool IsUserManaged
        {
            get
            {
                return this is UserManaged;
            }
        }

        /// <summary>
        /// <para>Gets this instance as a UserManaged, or <c>null</c>.</para>
        /// </summary>
        public UserManaged AsUserManaged
        {
            get
            {
                return this as UserManaged;
            }
        }

        /// <summary>
        /// <para>Gets a value indicating whether this instance is Other</para>
        /// </summary>
        public bool IsOther
        {
            get
            {
                return this is Other;
            }
        }

        /// <summary>
        /// <para>Gets this instance as a Other, or <c>null</c>.</para>
        /// </summary>
        public Other AsOther
        {
            get
            {
                return this as Other;
            }
        }

        #region Encoder class

        /// <summary>
        /// <para>Encoder for  <see cref="GroupManagementType" />.</para>
        /// </summary>
        private class GroupManagementTypeEncoder : enc.StructEncoder<GroupManagementType>
        {
            /// <summary>
            /// <para>Encode fields of given value.</para>
            /// </summary>
            /// <param name="value">The value.</param>
            /// <param name="writer">The writer.</param>
            public override void EncodeFields(GroupManagementType value, enc.IJsonWriter writer)
            {
                if (value is CompanyManaged)
                {
                    WriteProperty(".tag", "company_managed", writer, enc.StringEncoder.Instance);
                    CompanyManaged.Encoder.EncodeFields((CompanyManaged)value, writer);
                    return;
                }
                if (value is UserManaged)
                {
                    WriteProperty(".tag", "user_managed", writer, enc.StringEncoder.Instance);
                    UserManaged.Encoder.EncodeFields((UserManaged)value, writer);
                    return;
                }
                if (value is Other)
                {
                    WriteProperty(".tag", "other", writer, enc.StringEncoder.Instance);
                    Other.Encoder.EncodeFields((Other)value, writer);
                    return;
                }
                throw new sys.InvalidOperationException();
            }
        }

        #endregion

        #region Decoder class

        /// <summary>
        /// <para>Decoder for  <see cref="GroupManagementType" />.</para>
        /// </summary>
        private class GroupManagementTypeDecoder : enc.UnionDecoder<GroupManagementType>
        {
            /// <summary>
            /// <para>Create a new instance of type <see cref="GroupManagementType" />.</para>
            /// </summary>
            /// <returns>The struct instance.</returns>
            protected override GroupManagementType Create()
            {
                return new GroupManagementType();
            }

            /// <summary>
            /// <para>Decode based on given tag.</para>
            /// </summary>
            /// <param name="tag">The tag.</param>
            /// <param name="reader">The json reader.</param>
            /// <returns>The decoded object.</returns>
            protected override GroupManagementType Decode(string tag, enc.IJsonReader reader)
            {
                switch (tag)
                {
                    case "company_managed":
                        return CompanyManaged.Decoder.DecodeFields(reader);
                    case "user_managed":
                        return UserManaged.Decoder.DecodeFields(reader);
                    default:
                        return Other.Decoder.DecodeFields(reader);
                }
            }
        }

        #endregion

        /// <summary>
        /// <para>A group which is managed by team admins only.</para>
        /// </summary>
        public sealed class CompanyManaged : GroupManagementType
        {
            #pragma warning disable 108

            /// <summary>
            /// <para>The encoder instance.</para>
            /// </summary>
            internal static enc.StructEncoder<CompanyManaged> Encoder = new CompanyManagedEncoder();

            /// <summary>
            /// <para>The decoder instance.</para>
            /// </summary>
            internal static enc.StructDecoder<CompanyManaged> Decoder = new CompanyManagedDecoder();

            /// <summary>
            /// <para>Initializes a new instance of the <see cref="CompanyManaged" />
            /// class.</para>
            /// </summary>
            private CompanyManaged()
            {
            }

            /// <summary>
            /// <para>A singleton instance of CompanyManaged</para>
            /// </summary>
            public static readonly CompanyManaged Instance = new CompanyManaged();

            #region Encoder class

            /// <summary>
            /// <para>Encoder for  <see cref="CompanyManaged" />.</para>
            /// </summary>
            private class CompanyManagedEncoder : enc.StructEncoder<CompanyManaged>
            {
                /// <summary>
                /// <para>Encode fields of given value.</para>
                /// </summary>
                /// <param name="value">The value.</param>
                /// <param name="writer">The writer.</param>
                public override void EncodeFields(CompanyManaged value, enc.IJsonWriter writer)
                {
                }
            }

            #endregion

            #region Decoder class

            /// <summary>
            /// <para>Decoder for  <see cref="CompanyManaged" />.</para>
            /// </summary>
            private class CompanyManagedDecoder : enc.StructDecoder<CompanyManaged>
            {
                /// <summary>
                /// <para>Create a new instance of type <see cref="CompanyManaged" />.</para>
                /// </summary>
                /// <returns>The struct instance.</returns>
                protected override CompanyManaged Create()
                {
                    return new CompanyManaged();
                }

                /// <summary>
                /// <para>Decode fields without ensuring start and end object.</para>
                /// </summary>
                /// <param name="reader">The json reader.</param>
                /// <returns>The decoded object.</returns>
                public override CompanyManaged DecodeFields(enc.IJsonReader reader)
                {
                    return CompanyManaged.Instance;
                }
            }

            #endregion
        }

        /// <summary>
        /// <para>A group which is managed by selected users.</para>
        /// </summary>
        public sealed class UserManaged : GroupManagementType
        {
            #pragma warning disable 108

            /// <summary>
            /// <para>The encoder instance.</para>
            /// </summary>
            internal static enc.StructEncoder<UserManaged> Encoder = new UserManagedEncoder();

            /// <summary>
            /// <para>The decoder instance.</para>
            /// </summary>
            internal static enc.StructDecoder<UserManaged> Decoder = new UserManagedDecoder();

            /// <summary>
            /// <para>Initializes a new instance of the <see cref="UserManaged" />
            /// class.</para>
            /// </summary>
            private UserManaged()
            {
            }

            /// <summary>
            /// <para>A singleton instance of UserManaged</para>
            /// </summary>
            public static readonly UserManaged Instance = new UserManaged();

            #region Encoder class

            /// <summary>
            /// <para>Encoder for  <see cref="UserManaged" />.</para>
            /// </summary>
            private class UserManagedEncoder : enc.StructEncoder<UserManaged>
            {
                /// <summary>
                /// <para>Encode fields of given value.</para>
                /// </summary>
                /// <param name="value">The value.</param>
                /// <param name="writer">The writer.</param>
                public override void EncodeFields(UserManaged value, enc.IJsonWriter writer)
                {
                }
            }

            #endregion

            #region Decoder class

            /// <summary>
            /// <para>Decoder for  <see cref="UserManaged" />.</para>
            /// </summary>
            private class UserManagedDecoder : enc.StructDecoder<UserManaged>
            {
                /// <summary>
                /// <para>Create a new instance of type <see cref="UserManaged" />.</para>
                /// </summary>
                /// <returns>The struct instance.</returns>
                protected override UserManaged Create()
                {
                    return new UserManaged();
                }

                /// <summary>
                /// <para>Decode fields without ensuring start and end object.</para>
                /// </summary>
                /// <param name="reader">The json reader.</param>
                /// <returns>The decoded object.</returns>
                public override UserManaged DecodeFields(enc.IJsonReader reader)
                {
                    return UserManaged.Instance;
                }
            }

            #endregion
        }

        /// <summary>
        /// <para>The other object</para>
        /// </summary>
        public sealed class Other : GroupManagementType
        {
            #pragma warning disable 108

            /// <summary>
            /// <para>The encoder instance.</para>
            /// </summary>
            internal static enc.StructEncoder<Other> Encoder = new OtherEncoder();

            /// <summary>
            /// <para>The decoder instance.</para>
            /// </summary>
            internal static enc.StructDecoder<Other> Decoder = new OtherDecoder();

            /// <summary>
            /// <para>Initializes a new instance of the <see cref="Other" /> class.</para>
            /// </summary>
            private Other()
            {
            }

            /// <summary>
            /// <para>A singleton instance of Other</para>
            /// </summary>
            public static readonly Other Instance = new Other();

            #region Encoder class

            /// <summary>
            /// <para>Encoder for  <see cref="Other" />.</para>
            /// </summary>
            private class OtherEncoder : enc.StructEncoder<Other>
            {
                /// <summary>
                /// <para>Encode fields of given value.</para>
                /// </summary>
                /// <param name="value">The value.</param>
                /// <param name="writer">The writer.</param>
                public override void EncodeFields(Other value, enc.IJsonWriter writer)
                {
                }
            }

            #endregion

            #region Decoder class

            /// <summary>
            /// <para>Decoder for  <see cref="Other" />.</para>
            /// </summary>
            private class OtherDecoder : enc.StructDecoder<Other>
            {
                /// <summary>
                /// <para>Create a new instance of type <see cref="Other" />.</para>
                /// </summary>
                /// <returns>The struct instance.</returns>
                protected override Other Create()
                {
                    return new Other();
                }

                /// <summary>
                /// <para>Decode fields without ensuring start and end object.</para>
                /// </summary>
                /// <param name="reader">The json reader.</param>
                /// <returns>The decoded object.</returns>
                public override Other DecodeFields(enc.IJsonReader reader)
                {
                    return Other.Instance;
                }
            }

            #endregion
        }
    }
}
