// <auto-generated>
// Auto-generated by BabelAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api
{
    using sys = System;

    using Dropbox.Api.Babel;

    public sealed partial class DropboxTeamClient
    {

        /// <summary>
        /// <para>Initializes the routes.</para>
        /// </summary>
        /// <returns>The transport.</returns>
        private void InitializeRoutes(ITransport transport)
        {
        }
    }
}
