// <auto-generated>
// Auto-generated by BabelAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Files
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Babel;

    /// <summary>
    /// <para>The metadata with path object</para>
    /// </summary>
    /// <seealso cref="SearchMatch" />
    public sealed class MetadataWithPath : enc.IEncodable<MetadataWithPath>
    {
        /// <summary>
        /// <para>Initializes a new instance of the <see cref="MetadataWithPath" />
        /// class.</para>
        /// </summary>
        /// <param name="path">The path</param>
        /// <param name="metadata">The metadata</param>
        public MetadataWithPath(string path,
                                Metadata metadata)
        {
            if (path == null)
            {
                throw new sys.ArgumentNullException("path");
            }

            if (metadata == null)
            {
                throw new sys.ArgumentNullException("metadata");
            }

            this.Path = path;
            this.Metadata = metadata;
        }

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="MetadataWithPath" />
        /// class.</para>
        /// </summary>
        /// <remarks>This is to construct an instance of the object when
        /// deserializing.</remarks>
        public MetadataWithPath()
        {
        }

        /// <summary>
        /// <para>Gets the path of the metadata with path</para>
        /// </summary>
        public string Path { get; private set; }

        /// <summary>
        /// <para>Gets the metadata of the metadata with path</para>
        /// </summary>
        public Metadata Metadata { get; private set; }

        #region IEncodable<MetadataWithPath> methods

        /// <summary>
        /// <para>Encodes the object using the supplied encoder.</para>
        /// </summary>
        /// <param name="encoder">The encoder being used to serialize the object.</param>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        void enc.IEncodable<MetadataWithPath>.Encode(enc.IEncoder encoder)
        {
            using (var obj = encoder.AddObject())
            {
                obj.AddField<string>("path", this.Path);
                obj.AddFieldObject<Metadata>("metadata", this.Metadata);
            }
        }

        /// <summary>
        /// <para>Decodes on object using the supplied decoder.</para>
        /// </summary>
        /// <param name="decoder">The decoder used to deserialize the object.</param>
        /// <returns>The deserialized object. Note: this is not necessarily the current
        /// instance.</returns>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        MetadataWithPath enc.IEncodable<MetadataWithPath>.Decode(enc.IDecoder decoder)
        {
            using (var obj = decoder.GetObject())
            {
                this.Path = obj.GetField<string>("path");
                this.Metadata = obj.GetFieldObject<Metadata>("metadata");

                return this;
            }
        }

        #endregion
    }
}
