// <auto-generated>
// Auto-generated by BabelAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Files
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Babel;

    /// <summary>
    /// <para>The metadata with name object</para>
    /// </summary>
    public sealed class MetadataWithName : enc.IEncodable<MetadataWithName>
    {
        /// <summary>
        /// <para>Initializes a new instance of the <see cref="MetadataWithName" />
        /// class.</para>
        /// </summary>
        /// <param name="name">The name</param>
        /// <param name="metadata">The metadata</param>
        public MetadataWithName(string name,
                                Metadata metadata)
        {
            if (name == null)
            {
                throw new sys.ArgumentNullException("name");
            }

            if (metadata == null)
            {
                throw new sys.ArgumentNullException("metadata");
            }

            this.Name = name;
            this.Metadata = metadata;
        }

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="MetadataWithName" />
        /// class.</para>
        /// </summary>
        /// <remarks>This is to construct an instance of the object when
        /// deserializing.</remarks>
        public MetadataWithName()
        {
        }

        /// <summary>
        /// <para>Gets the name of the metadata with name</para>
        /// </summary>
        public string Name { get; private set; }

        /// <summary>
        /// <para>Gets the metadata of the metadata with name</para>
        /// </summary>
        public Metadata Metadata { get; private set; }

        #region IEncodable<MetadataWithName> methods

        /// <summary>
        /// <para>Encodes the object using the supplied encoder.</para>
        /// </summary>
        /// <param name="encoder">The encoder being used to serialize the object.</param>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        void enc.IEncodable<MetadataWithName>.Encode(enc.IEncoder encoder)
        {
            using (var obj = encoder.AddObject())
            {
                obj.AddField<string>("name", this.Name);
                obj.AddFieldObject<Metadata>("metadata", this.Metadata);
            }
        }

        /// <summary>
        /// <para>Decodes on object using the supplied decoder.</para>
        /// </summary>
        /// <param name="decoder">The decoder used to deserialize the object.</param>
        /// <returns>The deserialized object. Note: this is not necessarily the current
        /// instance.</returns>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        MetadataWithName enc.IEncodable<MetadataWithName>.Decode(enc.IDecoder decoder)
        {
            using (var obj = decoder.GetObject())
            {
                this.Name = obj.GetField<string>("name");
                this.Metadata = obj.GetFieldObject<Metadata>("metadata");

                return this;
            }
        }

        #endregion
    }
}
