// <auto-generated>
// Auto-generated by BabelAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Files
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Babel;

    /// <summary>
    /// <para>The no file object</para>
    /// </summary>
    public sealed class NoFile : enc.IEncodable<NoFile>
    {
        /// <summary>
        /// <para>Initializes a new instance of the <see cref="NoFile" /> class.</para>
        /// </summary>
        /// <param name="reason">The reason</param>
        public NoFile(NoFileReason reason)
        {
            if (reason == null)
            {
                throw new sys.ArgumentNullException("reason");
            }

            this.Reason = reason;
        }

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="NoFile" /> class.</para>
        /// </summary>
        /// <remarks>This is to construct an instance of the object when
        /// deserializing.</remarks>
        public NoFile()
        {
        }

        /// <summary>
        /// <para>Gets the reason of the no file</para>
        /// </summary>
        public NoFileReason Reason { get; private set; }

        #region IEncodable<NoFile> methods

        /// <summary>
        /// <para>Encodes the object using the supplied encoder.</para>
        /// </summary>
        /// <param name="encoder">The encoder being used to serialize the object.</param>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        void enc.IEncodable<NoFile>.Encode(enc.IEncoder encoder)
        {
            using (var obj = encoder.AddObject())
            {
                obj.AddFieldObject<NoFileReason>("reason", this.Reason);
            }
        }

        /// <summary>
        /// <para>Decodes on object using the supplied decoder.</para>
        /// </summary>
        /// <param name="decoder">The decoder used to deserialize the object.</param>
        /// <returns>The deserialized object. Note: this is not necessarily the current
        /// instance.</returns>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        NoFile enc.IEncodable<NoFile>.Decode(enc.IDecoder decoder)
        {
            using (var obj = decoder.GetObject())
            {
                this.Reason = obj.GetFieldObject<NoFileReason>("reason");

                return this;
            }
        }

        #endregion
    }
}
