// <auto-generated>
// Auto-generated by BabelAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Files
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Babel;

    /// <summary>
    /// <para>The restore arg object</para>
    /// </summary>
    public sealed class RestoreArg : enc.IEncodable<RestoreArg>
    {
        /// <summary>
        /// <para>Initializes a new instance of the <see cref="RestoreArg" /> class.</para>
        /// </summary>
        /// <param name="path">The path to the file you want to restore.</param>
        /// <param name="rev">The revision to restore for the file.</param>
        public RestoreArg(string path,
                          string rev)
        {
            if (path == null)
            {
                throw new sys.ArgumentNullException("path");
            }
            else if (!re.Regex.IsMatch(path, @"/.*"))
            {
                throw new sys.ArgumentOutOfRangeException("path");
            }

            if (rev == null)
            {
                throw new sys.ArgumentNullException("rev");
            }
            else if (rev.Length < 9 || !re.Regex.IsMatch(rev, @"[0-9a-f]+"))
            {
                throw new sys.ArgumentOutOfRangeException("rev");
            }

            this.Path = path;
            this.Rev = rev;
        }

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="RestoreArg" /> class.</para>
        /// </summary>
        /// <remarks>This is to construct an instance of the object when
        /// deserializing.</remarks>
        public RestoreArg()
        {
        }

        /// <summary>
        /// <para>The path to the file you want to restore.</para>
        /// </summary>
        public string Path { get; private set; }

        /// <summary>
        /// <para>The revision to restore for the file.</para>
        /// </summary>
        public string Rev { get; private set; }

        #region IEncodable<RestoreArg> methods

        /// <summary>
        /// <para>Encodes the object using the supplied encoder.</para>
        /// </summary>
        /// <param name="encoder">The encoder being used to serialize the object.</param>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        void enc.IEncodable<RestoreArg>.Encode(enc.IEncoder encoder)
        {
            using (var obj = encoder.AddObject())
            {
                obj.AddField<string>("path", this.Path);
                obj.AddField<string>("rev", this.Rev);
            }
        }

        /// <summary>
        /// <para>Decodes on object using the supplied decoder.</para>
        /// </summary>
        /// <param name="decoder">The decoder used to deserialize the object.</param>
        /// <returns>The deserialized object. Note: this is not necessarily the current
        /// instance.</returns>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        RestoreArg enc.IEncodable<RestoreArg>.Decode(enc.IDecoder decoder)
        {
            using (var obj = decoder.GetObject())
            {
                this.Path = obj.GetField<string>("path");
                this.Rev = obj.GetField<string>("rev");
            }

            return this;
        }

        #endregion
    }
}
