// <auto-generated>
// Auto-generated by BabelAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Files
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Babel;

    /// <summary>
    /// <para>The restore error object</para>
    /// </summary>
    public class RestoreError : enc.IEncodable<RestoreError>
    {
        /// <summary>
        /// <para>Initializes a new instance of the <see cref="RestoreError" /> class.</para>
        /// </summary>
        public RestoreError()
        {
        }

        /// <summary>
        /// <para>Gets a value indicating whether this instance is PathLookup</para>
        /// </summary>
        public bool IsPathLookup
        {
            get
            {
                return this is PathLookup;
            }
        }

        /// <summary>
        /// <para>Gets this instance as a PathLookup, or <c>null</c>.</para>
        /// </summary>
        public PathLookup AsPathLookup
        {
            get
            {
                return this as PathLookup;
            }
        }

        /// <summary>
        /// <para>Gets a value indicating whether this instance is PathWrite</para>
        /// </summary>
        public bool IsPathWrite
        {
            get
            {
                return this is PathWrite;
            }
        }

        /// <summary>
        /// <para>Gets this instance as a PathWrite, or <c>null</c>.</para>
        /// </summary>
        public PathWrite AsPathWrite
        {
            get
            {
                return this as PathWrite;
            }
        }

        /// <summary>
        /// <para>Gets a value indicating whether this instance is InvalidRevision</para>
        /// </summary>
        public bool IsInvalidRevision
        {
            get
            {
                return this is InvalidRevision;
            }
        }

        /// <summary>
        /// <para>Gets this instance as a InvalidRevision, or <c>null</c>.</para>
        /// </summary>
        public InvalidRevision AsInvalidRevision
        {
            get
            {
                return this as InvalidRevision;
            }
        }

        /// <summary>
        /// <para>Gets a value indicating whether this instance is Other</para>
        /// </summary>
        public bool IsOther
        {
            get
            {
                return this is Other;
            }
        }

        /// <summary>
        /// <para>Gets this instance as a Other, or <c>null</c>.</para>
        /// </summary>
        public Other AsOther
        {
            get
            {
                return this as Other;
            }
        }

        #region IEncodable<RestoreError> methods

        /// <summary>
        /// <para>Encodes the object using the supplied encoder.</para>
        /// </summary>
        /// <param name="encoder">The encoder being used to serialize the object.</param>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        void enc.IEncodable<RestoreError>.Encode(enc.IEncoder encoder)
        {
            if (this.IsPathLookup)
            {
                ((enc.IEncodable<PathLookup>)this).Encode(encoder);
            }
            else if (this.IsPathWrite)
            {
                ((enc.IEncodable<PathWrite>)this).Encode(encoder);
            }
            else if (this.IsInvalidRevision)
            {
                ((enc.IEncodable<InvalidRevision>)this).Encode(encoder);
            }
            else
            {
                ((enc.IEncodable<Other>)this).Encode(encoder);
            }
        }

        /// <summary>
        /// <para>Decodes on object using the supplied decoder.</para>
        /// </summary>
        /// <param name="decoder">The decoder used to deserialize the object.</param>
        /// <returns>The deserialized object. Note: this is not necessarily the current
        /// instance.</returns>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        RestoreError enc.IEncodable<RestoreError>.Decode(enc.IDecoder decoder)
        {
            switch (decoder.GetUnionName())
            {
            case "path_lookup":
                var pathLookup = new LookupError();
                return new PathLookup(((enc.IEncodable<LookupError>)pathLookup).Decode(decoder));
            case "path_write":
                var pathWrite = new WriteError();
                return new PathWrite(((enc.IEncodable<WriteError>)pathWrite).Decode(decoder));
            case "invalid_revision":
                return InvalidRevision.Instance;
            default:
                return Other.Instance;
            }
        }

        #endregion

        /// <summary>
        /// <para>An error occurs when downloading metadata for the file.</para>
        /// </summary>
        public sealed class PathLookup : RestoreError, enc.IEncodable<PathLookup>
        {
            /// <summary>
            /// <para>Initializes a new instance of the <see cref="PathLookup" /> class.</para>
            /// </summary>
            /// <param name="value">The value</param>
            public PathLookup(LookupError value)
            {
                this.Value = value;
            }

            /// <summary>
            /// <para>Gets the value of this instance.</para>
            /// </summary>
            public LookupError Value { get; private set; }

            /// <summary>
            /// <para>Encodes the object using the supplied encoder.</para>
            /// </summary>
            /// <param name="encoder">The encoder being used to serialize the object.</param>
            void enc.IEncodable<PathLookup>.Encode(enc.IEncoder encoder)
            {
                using (var obj = encoder.AddObject())
                {
                    obj.AddField(".tag", "path_lookup");
                    obj.AddField("path_lookup", this.Value);
                }
            }

            /// <summary>
            /// <para>Decodes on object using the supplied decoder.</para>
            /// </summary>
            /// <param name="decoder">The decoder used to deserialize the object.</param>
            /// <returns>The deserialized object. Note: this is not necessarily the current
            /// instance.</returns>
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
            PathLookup enc.IEncodable<PathLookup>.Decode(enc.IDecoder decoder)
            {
                throw new sys.InvalidOperationException("Decoding happens through the base class");
            }
        }

        /// <summary>
        /// <para>An error occurs when trying to restore the file to that path.</para>
        /// </summary>
        public sealed class PathWrite : RestoreError, enc.IEncodable<PathWrite>
        {
            /// <summary>
            /// <para>Initializes a new instance of the <see cref="PathWrite" /> class.</para>
            /// </summary>
            /// <param name="value">The value</param>
            public PathWrite(WriteError value)
            {
                this.Value = value;
            }

            /// <summary>
            /// <para>Gets the value of this instance.</para>
            /// </summary>
            public WriteError Value { get; private set; }

            /// <summary>
            /// <para>Encodes the object using the supplied encoder.</para>
            /// </summary>
            /// <param name="encoder">The encoder being used to serialize the object.</param>
            void enc.IEncodable<PathWrite>.Encode(enc.IEncoder encoder)
            {
                using (var obj = encoder.AddObject())
                {
                    obj.AddField(".tag", "path_write");
                    obj.AddField("path_write", this.Value);
                }
            }

            /// <summary>
            /// <para>Decodes on object using the supplied decoder.</para>
            /// </summary>
            /// <param name="decoder">The decoder used to deserialize the object.</param>
            /// <returns>The deserialized object. Note: this is not necessarily the current
            /// instance.</returns>
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
            PathWrite enc.IEncodable<PathWrite>.Decode(enc.IDecoder decoder)
            {
                throw new sys.InvalidOperationException("Decoding happens through the base class");
            }
        }

        /// <summary>
        /// <para>The revision is invalid. It may point to a different file.</para>
        /// </summary>
        public sealed class InvalidRevision : RestoreError, enc.IEncodable<InvalidRevision>
        {
            /// <summary>
            /// <para>Initializes a new instance of the <see cref="InvalidRevision" />
            /// class.</para>
            /// </summary>
            private InvalidRevision()
            {
            }

            /// <summary>
            /// <para>A singleton instance of InvalidRevision</para>
            /// </summary>
            public static readonly InvalidRevision Instance = new InvalidRevision();

            /// <summary>
            /// <para>Encodes the object using the supplied encoder.</para>
            /// </summary>
            /// <param name="encoder">The encoder being used to serialize the object.</param>
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
            void enc.IEncodable<InvalidRevision>.Encode(enc.IEncoder encoder)
            {
                using (var obj = encoder.AddObject())
                {
                    obj.AddField(".tag", "invalid_revision");
                }
            }

            /// <summary>
            /// <para>Decodes on object using the supplied decoder.</para>
            /// </summary>
            /// <param name="decoder">The decoder used to deserialize the object.</param>
            /// <returns>The deserialized object. Note: this is not necessarily the current
            /// instance.</returns>
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
            InvalidRevision enc.IEncodable<InvalidRevision>.Decode(enc.IDecoder decoder)
            {
                throw new sys.InvalidOperationException("Decoding happens through the base class");
            }
        }

        /// <summary>
        /// <para>The other object</para>
        /// </summary>
        public sealed class Other : RestoreError, enc.IEncodable<Other>
        {
            /// <summary>
            /// <para>Initializes a new instance of the <see cref="Other" /> class.</para>
            /// </summary>
            private Other()
            {
            }

            /// <summary>
            /// <para>A singleton instance of Other</para>
            /// </summary>
            public static readonly Other Instance = new Other();

            /// <summary>
            /// <para>Encodes the object using the supplied encoder.</para>
            /// </summary>
            /// <param name="encoder">The encoder being used to serialize the object.</param>
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
            void enc.IEncodable<Other>.Encode(enc.IEncoder encoder)
            {
                using (var obj = encoder.AddObject())
                {
                    obj.AddField(".tag", "other");
                }
            }

            /// <summary>
            /// <para>Decodes on object using the supplied decoder.</para>
            /// </summary>
            /// <param name="decoder">The decoder used to deserialize the object.</param>
            /// <returns>The deserialized object. Note: this is not necessarily the current
            /// instance.</returns>
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
            Other enc.IEncodable<Other>.Decode(enc.IDecoder decoder)
            {
                throw new sys.InvalidOperationException("Decoding happens through the base class");
            }
        }
    }
}
