// <auto-generated>
// Auto-generated by BabelAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Team
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Babel;

    /// <summary>
    /// <para>Error that can be raised when <see cref="GroupMemberSelector" /> is used, and the
    /// user is required to be a member of the specified group.</para>
    /// </summary>
    public class GroupMemberSelectorError
    {
        #pragma warning disable 108

        /// <summary>
        /// <para>The encoder instance.</para>
        /// </summary>
        internal static enc.StructEncoder<GroupMemberSelectorError> Encoder = new GroupMemberSelectorErrorEncoder();

        /// <summary>
        /// <para>The decoder instance.</para>
        /// </summary>
        internal static enc.StructDecoder<GroupMemberSelectorError> Decoder = new GroupMemberSelectorErrorDecoder();

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="GroupMemberSelectorError" />
        /// class.</para>
        /// </summary>
        public GroupMemberSelectorError()
        {
        }

        /// <summary>
        /// <para>Gets a value indicating whether this instance is MemberNotInGroup</para>
        /// </summary>
        public bool IsMemberNotInGroup
        {
            get
            {
                return this is MemberNotInGroup;
            }
        }

        /// <summary>
        /// <para>Gets this instance as a MemberNotInGroup, or <c>null</c>.</para>
        /// </summary>
        public MemberNotInGroup AsMemberNotInGroup
        {
            get
            {
                return this as MemberNotInGroup;
            }
        }

        #region Encoder class

        /// <summary>
        /// <para>Encoder for  <see cref="GroupMemberSelectorError" />.</para>
        /// </summary>
        private class GroupMemberSelectorErrorEncoder : enc.StructEncoder<GroupMemberSelectorError>
        {
            /// <summary>
            /// <para>Encode fields of given value.</para>
            /// </summary>
            /// <param name="value">The value.</param>
            /// <param name="writer">The writer.</param>
            public override void EncodeFields(GroupMemberSelectorError value, enc.IJsonWriter writer)
            {
                if (value is MemberNotInGroup)
                {
                    WriteProperty(".tag", "member_not_in_group", writer, enc.StringEncoder.Instance);
                    MemberNotInGroup.Encoder.EncodeFields((MemberNotInGroup)value, writer);
                    return;
                }
                throw new sys.InvalidOperationException();
            }
        }

        #endregion

        #region Decoder class

        /// <summary>
        /// <para>Decoder for  <see cref="GroupMemberSelectorError" />.</para>
        /// </summary>
        private class GroupMemberSelectorErrorDecoder : enc.UnionDecoder<GroupMemberSelectorError>
        {
            /// <summary>
            /// <para>Create a new instance of type <see cref="GroupMemberSelectorError"
            /// />.</para>
            /// </summary>
            /// <returns>The struct instance.</returns>
            protected override GroupMemberSelectorError Create()
            {
                return new GroupMemberSelectorError();
            }

            /// <summary>
            /// <para>Decode based on given tag.</para>
            /// </summary>
            /// <param name="tag">The tag.</param>
            /// <param name="reader">The json reader.</param>
            /// <returns>The decoded object.</returns>
            protected override GroupMemberSelectorError Decode(string tag, enc.IJsonReader reader)
            {
                switch (tag)
                {
                    case "member_not_in_group":
                        return MemberNotInGroup.Decoder.DecodeFields(reader);
                    default:
                        throw new sys.InvalidOperationException();
                }
            }
        }

        #endregion

        /// <summary>
        /// <para>The specified user is not a member of this group.</para>
        /// </summary>
        public sealed class MemberNotInGroup : GroupMemberSelectorError
        {
            #pragma warning disable 108

            /// <summary>
            /// <para>The encoder instance.</para>
            /// </summary>
            internal static enc.StructEncoder<MemberNotInGroup> Encoder = new MemberNotInGroupEncoder();

            /// <summary>
            /// <para>The decoder instance.</para>
            /// </summary>
            internal static enc.StructDecoder<MemberNotInGroup> Decoder = new MemberNotInGroupDecoder();

            /// <summary>
            /// <para>Initializes a new instance of the <see cref="MemberNotInGroup" />
            /// class.</para>
            /// </summary>
            private MemberNotInGroup()
            {
            }

            /// <summary>
            /// <para>A singleton instance of MemberNotInGroup</para>
            /// </summary>
            public static readonly MemberNotInGroup Instance = new MemberNotInGroup();

            #region Encoder class

            /// <summary>
            /// <para>Encoder for  <see cref="MemberNotInGroup" />.</para>
            /// </summary>
            private class MemberNotInGroupEncoder : enc.StructEncoder<MemberNotInGroup>
            {
                /// <summary>
                /// <para>Encode fields of given value.</para>
                /// </summary>
                /// <param name="value">The value.</param>
                /// <param name="writer">The writer.</param>
                public override void EncodeFields(MemberNotInGroup value, enc.IJsonWriter writer)
                {
                }
            }

            #endregion

            #region Decoder class

            /// <summary>
            /// <para>Decoder for  <see cref="MemberNotInGroup" />.</para>
            /// </summary>
            private class MemberNotInGroupDecoder : enc.StructDecoder<MemberNotInGroup>
            {
                /// <summary>
                /// <para>Create a new instance of type <see cref="MemberNotInGroup" />.</para>
                /// </summary>
                /// <returns>The struct instance.</returns>
                protected override MemberNotInGroup Create()
                {
                    return new MemberNotInGroup();
                }

                /// <summary>
                /// <para>Decode fields without ensuring start and end object.</para>
                /// </summary>
                /// <param name="reader">The json reader.</param>
                /// <returns>The decoded object.</returns>
                public override MemberNotInGroup DecodeFields(enc.IJsonReader reader)
                {
                    return MemberNotInGroup.Instance;
                }
            }

            #endregion
        }
    }
}
