// <auto-generated>
// Auto-generated by StoneAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Team
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Stone;

    /// <summary>
    /// <para>The list member apps result object</para>
    /// </summary>
    public class ListMemberAppsResult
    {
        #pragma warning disable 108

        /// <summary>
        /// <para>The encoder instance.</para>
        /// </summary>
        internal static enc.StructEncoder<ListMemberAppsResult> Encoder = new ListMemberAppsResultEncoder();

        /// <summary>
        /// <para>The decoder instance.</para>
        /// </summary>
        internal static enc.StructDecoder<ListMemberAppsResult> Decoder = new ListMemberAppsResultDecoder();

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="ListMemberAppsResult" />
        /// class.</para>
        /// </summary>
        /// <param name="linkedApiApps">List of third party applications linked by this team
        /// member</param>
        public ListMemberAppsResult(col.IEnumerable<ApiApp> linkedApiApps)
        {
            var linkedApiAppsList = enc.Util.ToList(linkedApiApps);

            if (linkedApiApps == null)
            {
                throw new sys.ArgumentNullException("linkedApiApps");
            }

            this.LinkedApiApps = linkedApiAppsList;
        }

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="ListMemberAppsResult" />
        /// class.</para>
        /// </summary>
        /// <remarks>This is to construct an instance of the object when
        /// deserializing.</remarks>
        public ListMemberAppsResult()
        {
        }

        /// <summary>
        /// <para>List of third party applications linked by this team member</para>
        /// </summary>
        public col.IList<ApiApp> LinkedApiApps { get; protected set; }

        #region Encoder class

        /// <summary>
        /// <para>Encoder for  <see cref="ListMemberAppsResult" />.</para>
        /// </summary>
        private class ListMemberAppsResultEncoder : enc.StructEncoder<ListMemberAppsResult>
        {
            /// <summary>
            /// <para>Encode fields of given value.</para>
            /// </summary>
            /// <param name="value">The value.</param>
            /// <param name="writer">The writer.</param>
            public override void EncodeFields(ListMemberAppsResult value, enc.IJsonWriter writer)
            {
                WriteListProperty("linked_api_apps", value.LinkedApiApps, writer, Dropbox.Api.Team.ApiApp.Encoder);
            }
        }

        #endregion


        #region Decoder class

        /// <summary>
        /// <para>Decoder for  <see cref="ListMemberAppsResult" />.</para>
        /// </summary>
        private class ListMemberAppsResultDecoder : enc.StructDecoder<ListMemberAppsResult>
        {
            /// <summary>
            /// <para>Create a new instance of type <see cref="ListMemberAppsResult" />.</para>
            /// </summary>
            /// <returns>The struct instance.</returns>
            protected override ListMemberAppsResult Create()
            {
                return new ListMemberAppsResult();
            }

            /// <summary>
            /// <para>Set given field.</para>
            /// </summary>
            /// <param name="value">The field value.</param>
            /// <param name="fieldName">The field name.</param>
            /// <param name="reader">The json reader.</param>
            protected override void SetField(ListMemberAppsResult value, string fieldName, enc.IJsonReader reader)
            {
                switch (fieldName)
                {
                    case "linked_api_apps":
                        value.LinkedApiApps = ReadList<ApiApp>(reader, Dropbox.Api.Team.ApiApp.Decoder);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }
        }

        #endregion
    }
}
