// <auto-generated>
// Auto-generated by StoneAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Team
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Stone;

    /// <summary>
    /// <para>Specify access type a member should have when joined to a group.</para>
    /// </summary>
    public class MemberAccess
    {
        #pragma warning disable 108

        /// <summary>
        /// <para>The encoder instance.</para>
        /// </summary>
        internal static enc.StructEncoder<MemberAccess> Encoder = new MemberAccessEncoder();

        /// <summary>
        /// <para>The decoder instance.</para>
        /// </summary>
        internal static enc.StructDecoder<MemberAccess> Decoder = new MemberAccessDecoder();

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="MemberAccess" /> class.</para>
        /// </summary>
        /// <param name="user">Identity of a user.</param>
        /// <param name="accessType">Access type.</param>
        public MemberAccess(UserSelectorArg user,
                            GroupAccessType accessType)
        {
            if (user == null)
            {
                throw new sys.ArgumentNullException("user");
            }

            if (accessType == null)
            {
                throw new sys.ArgumentNullException("accessType");
            }

            this.User = user;
            this.AccessType = accessType;
        }

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="MemberAccess" /> class.</para>
        /// </summary>
        /// <remarks>This is to construct an instance of the object when
        /// deserializing.</remarks>
        public MemberAccess()
        {
        }

        /// <summary>
        /// <para>Identity of a user.</para>
        /// </summary>
        public UserSelectorArg User { get; protected set; }

        /// <summary>
        /// <para>Access type.</para>
        /// </summary>
        public GroupAccessType AccessType { get; protected set; }

        #region Encoder class

        /// <summary>
        /// <para>Encoder for  <see cref="MemberAccess" />.</para>
        /// </summary>
        private class MemberAccessEncoder : enc.StructEncoder<MemberAccess>
        {
            /// <summary>
            /// <para>Encode fields of given value.</para>
            /// </summary>
            /// <param name="value">The value.</param>
            /// <param name="writer">The writer.</param>
            public override void EncodeFields(MemberAccess value, enc.IJsonWriter writer)
            {
                WriteProperty("user", value.User, writer, Dropbox.Api.Team.UserSelectorArg.Encoder);
                WriteProperty("access_type", value.AccessType, writer, Dropbox.Api.Team.GroupAccessType.Encoder);
            }
        }

        #endregion


        #region Decoder class

        /// <summary>
        /// <para>Decoder for  <see cref="MemberAccess" />.</para>
        /// </summary>
        private class MemberAccessDecoder : enc.StructDecoder<MemberAccess>
        {
            /// <summary>
            /// <para>Create a new instance of type <see cref="MemberAccess" />.</para>
            /// </summary>
            /// <returns>The struct instance.</returns>
            protected override MemberAccess Create()
            {
                return new MemberAccess();
            }

            /// <summary>
            /// <para>Set given field.</para>
            /// </summary>
            /// <param name="value">The field value.</param>
            /// <param name="fieldName">The field name.</param>
            /// <param name="reader">The json reader.</param>
            protected override void SetField(MemberAccess value, string fieldName, enc.IJsonReader reader)
            {
                switch (fieldName)
                {
                    case "user":
                        value.User = Dropbox.Api.Team.UserSelectorArg.Decoder.Decode(reader);
                        break;
                    case "access_type":
                        value.AccessType = Dropbox.Api.Team.GroupAccessType.Decoder.Decode(reader);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }
        }

        #endregion
    }
}
