// <auto-generated>
// Auto-generated by StoneAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Team
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Stone;

    /// <summary>
    /// <para>The team folder id list arg object</para>
    /// </summary>
    public class TeamFolderIdListArg
    {
        #pragma warning disable 108

        /// <summary>
        /// <para>The encoder instance.</para>
        /// </summary>
        internal static enc.StructEncoder<TeamFolderIdListArg> Encoder = new TeamFolderIdListArgEncoder();

        /// <summary>
        /// <para>The decoder instance.</para>
        /// </summary>
        internal static enc.StructDecoder<TeamFolderIdListArg> Decoder = new TeamFolderIdListArgDecoder();

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="TeamFolderIdListArg" />
        /// class.</para>
        /// </summary>
        /// <param name="teamFolderIds">The list of team folder IDs.</param>
        public TeamFolderIdListArg(col.IEnumerable<string> teamFolderIds)
        {
            var teamFolderIdsList = enc.Util.ToList(teamFolderIds);

            if (teamFolderIds == null)
            {
                throw new sys.ArgumentNullException("teamFolderIds");
            }
            if (teamFolderIdsList.Count < 1)
            {
                throw new sys.ArgumentOutOfRangeException("teamFolderIds", "List should at at least 1 items");
            }

            this.TeamFolderIds = teamFolderIdsList;
        }

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="TeamFolderIdListArg" />
        /// class.</para>
        /// </summary>
        /// <remarks>This is to construct an instance of the object when
        /// deserializing.</remarks>
        public TeamFolderIdListArg()
        {
        }

        /// <summary>
        /// <para>The list of team folder IDs.</para>
        /// </summary>
        public col.IList<string> TeamFolderIds { get; protected set; }

        #region Encoder class

        /// <summary>
        /// <para>Encoder for  <see cref="TeamFolderIdListArg" />.</para>
        /// </summary>
        private class TeamFolderIdListArgEncoder : enc.StructEncoder<TeamFolderIdListArg>
        {
            /// <summary>
            /// <para>Encode fields of given value.</para>
            /// </summary>
            /// <param name="value">The value.</param>
            /// <param name="writer">The writer.</param>
            public override void EncodeFields(TeamFolderIdListArg value, enc.IJsonWriter writer)
            {
                WriteListProperty("team_folder_ids", value.TeamFolderIds, writer, enc.StringEncoder.Instance);
            }
        }

        #endregion


        #region Decoder class

        /// <summary>
        /// <para>Decoder for  <see cref="TeamFolderIdListArg" />.</para>
        /// </summary>
        private class TeamFolderIdListArgDecoder : enc.StructDecoder<TeamFolderIdListArg>
        {
            /// <summary>
            /// <para>Create a new instance of type <see cref="TeamFolderIdListArg" />.</para>
            /// </summary>
            /// <returns>The struct instance.</returns>
            protected override TeamFolderIdListArg Create()
            {
                return new TeamFolderIdListArg();
            }

            /// <summary>
            /// <para>Set given field.</para>
            /// </summary>
            /// <param name="value">The field value.</param>
            /// <param name="fieldName">The field name.</param>
            /// <param name="reader">The json reader.</param>
            protected override void SetField(TeamFolderIdListArg value, string fieldName, enc.IJsonReader reader)
            {
                switch (fieldName)
                {
                    case "team_folder_ids":
                        value.TeamFolderIds = ReadList<string>(reader, enc.StringDecoder.Instance);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }
        }

        #endregion
    }
}
