// <auto-generated>
// Auto-generated by BabelAPI, do not modify.
// </auto-generated>

namespace Dropbox.Api.Team
{
    using sys = System;
    using col = System.Collections.Generic;
    using re = System.Text.RegularExpressions;

    using enc = Dropbox.Api.Babel;

    /// <summary>
    /// <para>Policies governing team members.</para>
    /// </summary>
    /// <seealso cref="TeamGetInfoResult" />
    public class TeamPolicies
    {
        #pragma warning disable 108

        /// <summary>
        /// <para>The encoder instance.</para>
        /// </summary>
        internal static enc.StructEncoder<TeamPolicies> Encoder = new TeamPoliciesEncoder();

        /// <summary>
        /// <para>The decoder instance.</para>
        /// </summary>
        internal static enc.StructDecoder<TeamPolicies> Decoder = new TeamPoliciesDecoder();

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="TeamPolicies" /> class.</para>
        /// </summary>
        /// <param name="sharing">Policies governing sharing.</param>
        /// <param name="emmState">This describes the Enterprise Mobility Management (EMM)
        /// state for this team. This information can be used to understand if an organization
        /// is integrating with a third-party EMM vendor to further manage and apply
        /// restrictions upon the team's Dropbox usage on mobile devices. This is a new feature
        /// and in the future we'll be adding more new fields and additional
        /// documentation.</param>
        public TeamPolicies(TeamSharingPolicies sharing,
                            EmmState emmState)
        {
            if (sharing == null)
            {
                throw new sys.ArgumentNullException("sharing");
            }

            if (emmState == null)
            {
                throw new sys.ArgumentNullException("emmState");
            }

            this.Sharing = sharing;
            this.EmmState = emmState;
        }

        /// <summary>
        /// <para>Initializes a new instance of the <see cref="TeamPolicies" /> class.</para>
        /// </summary>
        /// <remarks>This is to construct an instance of the object when
        /// deserializing.</remarks>
        public TeamPolicies()
        {
        }

        /// <summary>
        /// <para>Policies governing sharing.</para>
        /// </summary>
        public TeamSharingPolicies Sharing { get; protected set; }

        /// <summary>
        /// <para>This describes the Enterprise Mobility Management (EMM) state for this team.
        /// This information can be used to understand if an organization is integrating with a
        /// third-party EMM vendor to further manage and apply restrictions upon the team's
        /// Dropbox usage on mobile devices. This is a new feature and in the future we'll be
        /// adding more new fields and additional documentation.</para>
        /// </summary>
        public EmmState EmmState { get; protected set; }

        #region Encoder class

        /// <summary>
        /// <para>Encoder for  <see cref="TeamPolicies" />.</para>
        /// </summary>
        private class TeamPoliciesEncoder : enc.StructEncoder<TeamPolicies>
        {
            /// <summary>
            /// <para>Encode fields of given value.</para>
            /// </summary>
            /// <param name="value">The value.</param>
            /// <param name="writer">The writer.</param>
            public override void EncodeFields(TeamPolicies value, enc.IJsonWriter writer)
            {
                WriteProperty("sharing", value.Sharing, writer, Dropbox.Api.Team.TeamSharingPolicies.Encoder);
                WriteProperty("emm_state", value.EmmState, writer, Dropbox.Api.Team.EmmState.Encoder);
            }
        }

        #endregion


        #region Decoder class

        /// <summary>
        /// <para>Decoder for  <see cref="TeamPolicies" />.</para>
        /// </summary>
        private class TeamPoliciesDecoder : enc.StructDecoder<TeamPolicies>
        {
            /// <summary>
            /// <para>Create a new instance of type <see cref="TeamPolicies" />.</para>
            /// </summary>
            /// <returns>The struct instance.</returns>
            protected override TeamPolicies Create()
            {
                return new TeamPolicies();
            }

            /// <summary>
            /// <para>Set given field.</para>
            /// </summary>
            /// <param name="value">The field value.</param>
            /// <param name="fieldName">The field name.</param>
            /// <param name="reader">The json reader.</param>
            protected override void SetField(TeamPolicies value, string fieldName, enc.IJsonReader reader)
            {
                switch (fieldName)
                {
                    case "sharing":
                        value.Sharing = Dropbox.Api.Team.TeamSharingPolicies.Decoder.Decode(reader);
                        break;
                    case "emm_state":
                        value.EmmState = Dropbox.Api.Team.EmmState.Decoder.Decode(reader);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }
        }

        #endregion
    }
}
