name: CodeCov
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  Unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: |
          dotnet test \
          dropbox-sdk-dotnet/Dropbox.Api.Unit.Tests \
          --collect:"XPlat Code Coverage" \
          -- \
          'DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.ExcludeByFile=**/Generated/**/*.cs'
      - name: Publish Coverage
        uses: codecov/codecov-action@v1.2.0
        with:
          flags: unit
          fail_ci_if_error: true
          directory: dropbox-sdk-dotnet/Dropbox.Api.Unit.Tests/TestResults/
