name: Publish to NuGet

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:  # required for OIDC authentication
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: NuGet login (Trusted Publishing via OIDC)
        uses: NuGet/login@v1
        id: login
        with:
          user: dropbox
      - name: Pack
        run: |
          dotnet pack \
          dropbox-sdk-dotnet/Dropbox.Api \
          -p:Configuration=Release \
          -p:Version=$(echo "${{ github.event.release.tag_name }}" | cut -c 2-) \
          -p:AssemblyOriginatorKeyFile=dropbox_api_key.snk \
          -p:SignAssembly=true
      - name: Push
        run: |
          dotnet nuget push \
          dropbox-sdk-dotnet/Dropbox.Api/bin/Release/Dropbox.Api.$(echo "${{ github.event.release.tag_name }}" | cut -c 2-).nupkg \
          --source https://api.nuget.org/v3/index.json \
          --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
